version: "3"

services:

  #php server
  baka-http:
    image: mctekk/phalconphp:latest
    volumes:
      - .:/app
      - ../../baka:/baka
    depends_on:
      - 'redis'
      - 'mysql'
    tty: true
    ports:
      - "9000:9000"
    networks:
      - local-network

  nginx:
    image: nginx:latest
    ports:
        - "80:80"
    links:
        - baka-http
    volumes:
        - .:/app
        - ./storage/ci/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - local-network
      - public-network

  redis:
    image: 'redis:5.0.5-alpine'
    ports: 
      - "6379:6379"
    volumes:
      - 'redis:/data'
    networks:
      - local-network

  memcached:
    image: memcached
    ports:
      - "11211:11211"
    networks:
      - local-network

  mysql:
    image: mariadb:10.4
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - '.env'
    volumes:
      - "db-data:/var/lib/mysql"
    networks:
        - local-network

volumes:
  db-data:
  redis:

networks:
  local-network:
  public-network:
